### PR TITLE
Cosmetic changes in "Upload File" section of the web interface

### PR DESCRIPTION
**Pull request by Mati20187**
Makes the "upload" button fit in the frame instead of sticking out and changes its color

### CODE REVIEW

**Comment by TerryGeng** [comment]
Hi, thanks for the PR.

I use chrome and this is what it is like in my browser:
image

Before your changes, it should look like:
image

I'm not very sure what's your goal. Could you make the "upload to" part longer as well to fit the outer box?

**Comment by Mati20187** [comment]
It seems like there are some inconsistencies between different browsers. Here's what it looks like on Firefox before the changes:
firefox-before
and after:
firefox-after
I'm gonna download Firefox Nightly and check there because I have quite a lot of extensions on my Firefox and some of them might be messing things up

**Comment by Mati20187** [comment]
I checked on Firefox Nightly and the problem still occurs. Could you send me a screenshot of the full page? Because I'm starting to think that the default column width on Chrome and Firefox may be different.
botamusique

**Comment by Mati20187** [comment]
I've managed to find the exact cause of the issue but I have no idea how to fix it.
It looks like Chrome-based browsers (in my case qutebrowser) include the "Upload" "button in col-lg-4 input-group-append" whereas Firefox doesn't. Take a look.
Firefox:
firefox-botamusique
QuteBrowser:
qb-botamusique

**Comment by TerryGeng** [comment]
Thanks for trying different browsers. I will have a look shortly to see if I can find any workaround.

**Comment by TerryGeng** [comment]
Hi, I tried some ways. This one limits the width of the upload box and is likely to fix the problem on Firefox. I personally believe this is actually a bug of Firefox. Anyway, please check this out.

**Comment by Mati20187** [comment]
It has fixed the problem. If I were you I'd also change the "Upload" button to blue to fit the rest of the page but that's purely cosmetic.

As soon as I have enough free time, I'll go over all the functions of the bot and let you know whether everything is working as expected because, as you said, you may have a hard time checking Youtube and Soundcloud related options yourself because of the proxies

**Comment by TerryGeng** [comment]
Actually, from my personal aesthetic view, I think the white button looks good. While some of my friends did feel confused since it doesn't look like a button. I changed it to blue and also fixed some margin problems.

**Comment by Mati20187** [comment]
I don't have a way to contact you so I'm gonna write it here. Playlists are not working again. Log:
```
[Feb 22 21:37:15 INFO MainThread] bot: botamusique version 5, starting...
[Feb 22 21:37:15 DEBUG MainThread] Starting in DEBUG loglevel
[Feb 22 21:37:15 INFO WebThread] Starting web interface on 192.168.0.102:8181
 * Serving Flask app "interface" (lazy loading)
[Feb 22 21:37:15 DEBUG UpdateThread] update: checking for updates...
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
[Feb 22 21:37:15 INFO WebThread]  * Running on http://192.168.0.102:8181/ (Press CTRL+C to quit)
[Feb 22 21:37:15 DEBUG MainThread] bot: command added: joinme
[Feb 22 21:37:15 DEBUG MainThread] bot: command added: userban
[Feb 22 21:37:15 DEBUG MainThread] bot: command added: userunban
[Feb 22 21:37:15 DEBUG MainThread] bot: command added: urlban
[Feb 22 21:37:15 DEBUG MainThread] bot: command added: urlunban
[Feb 22 21:37:15 DEBUG MainThread] bot: command added: p
[Feb 22 21:37:15 DEBUG MainThread] bot: command added: play
[Feb 22 21:37:15 DEBUG MainThread] bot: command added: pause
[Feb 22 21:37:15 DEBUG MainThread] bot: command added: file
[Feb 22 21:37:15 DEBUG MainThread] bot: command added: f
[Feb 22 21:37:15 DEBUG MainThread] bot: command added: filematch
[Feb 22 21:37:15 DEBUG MainThread] bot: command added: fm
[Feb 22 21:37:15 DEBUG MainThread] bot: command added: url
[Feb 22 21:37:15 DEBUG MainThread] bot: command added: playlist
[Feb 22 21:37:15 DEBUG MainThread] bot: command added: radio
[Feb 22 21:37:15 DEBUG MainThread] bot: command added: rbquery
[Feb 22 21:37:15 DEBUG MainThread] bot: command added: rbplay
[Feb 22 21:37:15 DEBUG MainThread] bot: command added: help
[Feb 22 21:37:15 DEBUG MainThread] bot: command added: stop
[Feb 22 21:37:15 DEBUG MainThread] bot: command added: clear
[Feb 22 21:37:15 DEBUG MainThread] bot: command added: kill
[Feb 22 21:37:15 DEBUG MainThread] bot: command added: update
[Feb 22 21:37:15 DEBUG MainThread] bot: command added: oust
[Feb 22 21:37:15 DEBUG MainThread] bot: command added: volume
[Feb 22 21:37:15 DEBUG MainThread] bot: command added: duck
[Feb 22 21:37:15 DEBUG MainThread] bot: command added: duckthres
[Feb 22 21:37:15 DEBUG MainThread] bot: command added: duckv
[Feb 22 21:37:15 DEBUG MainThread] bot: command added: np
[Feb 22 21:37:15 DEBUG MainThread] bot: command added: now
[Feb 22 21:37:15 DEBUG MainThread] bot: command added: skip
[Feb 22 21:37:15 DEBUG MainThread] bot: command added: rm
[Feb 22 21:37:15 DEBUG MainThread] bot: command added: listfile
[Feb 22 21:37:15 DEBUG MainThread] bot: command added: queue
[Feb 22 21:37:15 DEBUG MainThread] bot: command added: random
[Feb 22 21:37:15 DEBUG MainThread] bot: command added: dropdatabase
[Feb 22 21:37:15 INFO MainThread] bot: load playlist from previous session
[Feb 22 21:37:15 DEBUG Thread-1] bot: ducking triggered
[Feb 22 21:37:15 DEBUG UpdateThread] update: no new version found.
[Feb 22 21:37:26 INFO Thread-2] bot: received command playlist - <a href="https://www.youtube.com/playlist?list=PL1qiB_iRKQOi3gq0V1Tf5CG2o02wF0rdy">https://www.youtube.com/playlist?list=PL1qiB_iRKQOi3gq0V1Tf5CG2o02wF0rdy</a> by Mati
[Feb 22 21:37:26 DEBUG Thread-2] cmd: fetching media info from playlist url https://www.youtube.com/playlist?list=PL1qiB_iRKQOi3gq0V1Tf5CG2o02wF0rdy
[youtube:playlist] PL1qiB_iRKQOi3gq0V1Tf5CG2o02wF0rdy: Downloading webpage
[download] Downloading playlist: Music
[youtube:playlist] PL1qiB_iRKQOi3gq0V1Tf5CG2o02wF0rdy: Downloading page #1
[youtube:playlist] playlist Music: Downloading 104 videos
[download] Downloading video 1 of 104
[download] Downloading video 2 of 104
[download] Downloading video 3 of 104
[download] Downloading video 4 of 104
[download] Downloading video 5 of 104
[download] Downloading video 6 of 104
[download] Downloading video 7 of 104
[download] Downloading video 8 of 104
[download] Downloading video 9 of 104
[download] Downloading video 10 of 104
[download] Downloading video 11 of 104
[download] Downloading video 12 of 104
[download] Downloading video 13 of 104
[download] Downloading video 14 of 104
[download] Downloading video 15 of 104
[download] Downloading video 16 of 104
[download] Downloading video 17 of 104
[download] Downloading video 18 of 104
[download] Downloading video 19 of 104
[download] Downloading video 20 of 104
[download] Downloading video 21 of 104
[download] Downloading video 22 of 104
[download] Downloading video 23 of 104
[download] Downloading video 24 of 104
[download] Downloading video 25 of 104
[download] Downloading video 26 of 104
[download] Downloading video 27 of 104
[download] Downloading video 28 of 104
[download] Downloading video 29 of 104
[download] Downloading video 30 of 104
[download] Downloading video 31 of 104
[download] Downloading video 32 of 104
[download] Downloading video 33 of 104
[download] Downloading video 34 of 104
[download] Downloading video 35 of 104
[download] Downloading video 36 of 104
[download] Downloading video 37 of 104
[download] Downloading video 38 of 104
[download] Downloading video 39 of 104
[download] Downloading video 40 of 104
[download] Downloading video 41 of 104
[download] Downloading video 42 of 104
[download] Downloading video 43 of 104
[download] Downloading video 44 of 104
[download] Downloading video 45 of 104
[download] Downloading video 46 of 104
[download] Downloading video 47 of 104
[download] Downloading video 48 of 104
[download] Downloading video 49 of 104
[download] Downloading video 50 of 104
[download] Downloading video 51 of 104
[download] Downloading video 52 of 104
[download] Downloading video 53 of 104
[download] Downloading video 54 of 104
[download] Downloading video 55 of 104
[download] Downloading video 56 of 104
[download] Downloading video 57 of 104
[download] Downloading video 58 of 104
[download] Downloading video 59 of 104
[download] Downloading video 60 of 104
[download] Downloading video 61 of 104
[download] Downloading video 62 of 104
[download] Downloading video 63 of 104
[download] Downloading video 64 of 104
[download] Downloading video 65 of 104
[download] Downloading video 66 of 104
[download] Downloading video 67 of 104
[download] Downloading video 68 of 104
[download] Downloading video 69 of 104
[download] Downloading video 70 of 104
[download] Downloading video 71 of 104
[download] Downloading video 72 of 104
[download] Downloading video 73 of 104
[download] Downloading video 74 of 104
[download] Downloading video 75 of 104
[download] Downloading video 76 of 104
[download] Downloading video 77 of 104
[download] Downloading video 78 of 104
[download] Downloading video 79 of 104
[download] Downloading video 80 of 104
[download] Downloading video 81 of 104
[download] Downloading video 82 of 104
[download] Downloading video 83 of 104
[download] Downloading video 84 of 104
[download] Downloading video 85 of 104
[download] Downloading video 86 of 104
[download] Downloading video 87 of 104
[download] Downloading video 88 of 104
[download] Downloading video 89 of 104
[download] Downloading video 90 of 104
[download] Downloading video 91 of 104
[download] Downloading video 92 of 104
[download] Downloading video 93 of 104
[download] Downloading video 94 of 104
[download] Downloading video 95 of 104
[download] Downloading video 96 of 104
[download] Downloading video 97 of 104
[download] Downloading video 98 of 104
[download] Downloading video 99 of 104
[download] Downloading video 100 of 104
[download] Downloading video 101 of 104
[download] Downloading video 102 of 104
[download] Downloading video 103 of 104
[download] Downloading video 104 of 104
[download] Finished downloading playlist: Music
[youtube] 4XBB8CNHs4U: Downloading webpage
[youtube] 4XBB8CNHs4U: Downloading embed webpage
[youtube] 4XBB8CNHs4U: Refetching age-gated info webpage
[Feb 22 21:37:30 INFO Thread-2] cmd: add to playlist: Neil Cicierega - AC/VC (Music Video) (https://www.youtube.com/watch?v=DgLS1kHiVcA)
[Feb 22 21:37:30 INFO Thread-2] cmd: add to playlist: Janis Joplin Piece Of My Heart HQ (https://www.youtube.com/watch?v=3SL0oRcD7t0)
[Feb 22 21:37:30 INFO Thread-2] cmd: add to playlist: Behemoth - Lucifer (lyric video/tekst) (https://www.youtube.com/watch?v=SkcNgQwSEbQ)
[Feb 22 21:37:30 INFO Thread-2] cmd: add to playlist: Feel It Still - Portugal. The Man - Drum Cover (https://www.youtube.com/watch?v=P4bVm5FH2mA)
[Feb 22 21:37:30 INFO Thread-2] cmd: add to playlist: Behemoth-Demigod(Radio D#$&ey Version) (https://www.youtube.com/watch?v=E92zCs4sWto)
[Feb 22 21:37:30 INFO Thread-2] cmd: add to playlist: WOODJU - Irradiant (https://www.youtube.com/watch?v=-UfITx3pFwY)
[Feb 22 21:37:30 INFO Thread-2] cmd: add to playlist: Epic Dark Battle Music • "Where Is Your God Now" by Rok Nardin (https://www.youtube.com/watch?v=bsvzP8EO65w)
[Feb 22 21:37:30 INFO Thread-2] cmd: add to playlist: Most Epic Battle Music Ever: "Deadwood" by Really Slow Motion (https://www.youtube.com/watch?v=LO3LZohKCnE)
[Feb 22 21:37:30 INFO Thread-2] cmd: add to playlist: Ганджу - V Λ C U U M [Visual Video Production(КЛИП)] (https://www.youtube.com/watch?v=bJOEAhB7eP8)
[Feb 22 21:37:30 INFO Thread-2] cmd: add to playlist: I'll Be There (Lyric Video) - Walk Off the Earth (https://www.youtube.com/watch?v=tRwMD-hCtjk)
[Feb 22 21:37:30 INFO Thread-2] cmd: add to playlist: Somebody That I Used to Know - Walk off the Earth (Gotye - Cover) (https://www.youtube.com/watch?v=P9mybTArlsk)
[Feb 22 21:37:30 INFO Thread-2] cmd: add to playlist: Gabriela Bee - Feelin' Alright (Official Music Video) (https://www.youtube.com/watch?v=O2Zchnm4S9U)
[Feb 22 21:37:30 INFO Thread-2] cmd: add to playlist: Karma Police - Gianni and Sarah (Walk off the Earth) (https://www.youtube.com/watch?v=yE2kANx8WdA)
[Feb 22 21:37:30 INFO Thread-2] cmd: add to playlist: Payphone - Walk off the Earth (Maroon 5 Cover) (https://www.youtube.com/watch?v=CEdD2_pdG_c)
[Feb 22 21:37:30 INFO Thread-2] cmd: add to playlist: I'll Be There - Walk Off The Earth (VR180) (https://www.youtube.com/watch?v=zCb4yRPYpiI)
[Feb 22 21:37:30 INFO Thread-2] cmd: add to playlist: Rude - Walk off the Earth (https://www.youtube.com/watch?v=I3W3mRs4ULQ)
[Feb 22 21:37:30 INFO Thread-2] cmd: add to playlist: Somebody That I Used to Know - Walk off the Earth (https://www.youtube.com/watch?v=d9NF2edxy-M)
[Feb 22 21:37:30 INFO Thread-2] cmd: add to playlist: Girls Like You - Walk off the Earth (Maroon 5 Cover) (https://www.youtube.com/watch?v=e3PcnNiWygw)
[Feb 22 21:37:30 INFO Thread-2] cmd: add to playlist: Feelin' alright - Gabriela Bee - Drum Cover (https://www.youtube.com/watch?v=aIISZkixg2M)
[Feb 22 21:37:30 INFO Thread-2] cmd: add to playlist: Me And That Man - My Church Is Black (Official Video) (https://www.youtube.com/watch?v=4XBB8CNHs4U)
[Feb 22 21:37:30 INFO Thread-2] cmd: add to playlist: Me And That Man - My Church Is Black (Official Video) (https://www.youtube.com/watch?v=4XBB8CNHs4U)
[Feb 22 21:37:30 INFO MainThread] bot: play music [url] Neil Cicierega - AC/VC (Music Video) (https://www.youtube.com/watch?v=DgLS1kHiVcA) from playlist Music by Mati
[Feb 22 21:37:30 INFO MainThread] bot: current music isn't ready, downloading...
[Feb 22 21:37:30 INFO MainThread] bot: verifying the duration of url (Neil Cicierega - AC/VC (Music Video)) https://www.youtube.com/watch?v=DgLS1kHiVcA 
<media.playlist.PlayList object at 0xb4b0fbf0>
[youtube] DgLS1kHiVcA: Downloading webpage
[youtube] DgLS1kHiVcA: Downloading video info webpage
[youtube] Downloading just video DgLS1kHiVcA because of --no-playlist
[youtube] DgLS1kHiVcA: Downloading MPD manifest
Traceback (most recent call last):
  File "/home/pi/botamusique/mumbleBot.py", line 705, in <module>
    var.botamusique.loop()
  File "/home/pi/botamusique/mumbleBot.py", line 564, in loop
    self.launch_music()
  File "/home/pi/botamusique/mumbleBot.py", line 320, in launch_music
    logging.info("bot: removing music from the playlist: %s" % util.format_debug_song_string(music))
  File "/home/pi/botamusique/util.py", line 151, in format_debug_song_string
    source = music["type"]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by TerryGeng** [comment]
Wow. You discovered a series of very subtle bugs. Today my proxy was like on fire and I was able to go through the entire playlist part and fixed all known bugs related to it. Please have a look. I hope this is the last time I fix the playlist stuff.

**Comment by TerryGeng** [comment]
Next time you find a big please just post it to mu PR at [@azlux 's repo.](https://github.com/azlux/botamusique/pulls) If azlux merged my PL, I think I will delete my fork and open a new "develop" branch under his repo and you can start an issue there.

**Pull request closed without merging**
